### ISSUE TITLE
Can't be installed in Debian11: xbmc.python in version 2.25.0 can't be resolved

### ISSUE THREAD

**Issue by mYnDstrEAm** [dojomo/plugin.video.mediathekdirekt#3]
Kodi 19 is in the Debian repos. This is in the Kodi logs:

```
CAddonInstaller: installing from zip '/home/username/plugin.video.mediathekdirekt-0.0.15.zip'
DEBUG <general>: Thread JobWorker start, auto delete: true
DEBUG <general>: CAddonInstallJob[plugin.video.mediathekdirekt]: requires xbmc.python version 2.25.0 which is not available
ERROR <general>: CAddonInstallJob[plugin.video.mediathekdirekt]: Die Abhängigkeit auf xbmc.python in Version 2.25.0 konnte nicht aufgelöst werden.
```

**Comment by dojomo** [comment]
Since Version Kodi 19 (Matrix) Kodi uses python 3.
You are trying to install an old version (0.0.15) of mediathekdirekt. Please use the newest release. You can find it here: https://github.com/dojomo/plugin.video.mediathekdirekt/tags
For all Kodi Versions since 19+ you need the newest Version ending with +matrix. Currently [1.0.2+matrix](https://github.com/dojomo/plugin.video.mediathekdirekt/releases/tag/1.0.2%2Bmatrix).
